create table if not exists ticket (
    id bigint generated by default as identity,
    body varchar(255),
    name varchar(255),
    subject varchar(255),
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    primary key (id)
   );
create table if not exists attachment (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    ticket_id bigint,
    primary key (id),
    foreign key (ticket_id) references ticket
);
create table if not exists users (
    username varchar(50) NOT NULL,
    password varchar(100) NOT NULL,
    comfirm_password varchar(100) NOT NULL,
    full_name varchar(100) NOT NULL,
    email_address varchar(255) NOT NULL,
    delivery_address varchar(255) NOT NULL,
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    primary key (username)
);
create table if not exists user_roles (
    user_role_id int generated always as identity,
    username varchar(50) not null,
    full_name varchar(100) NOT NULL,
    email_address varchar(255) NOT NULL,
    delivery_address varchar(255) NOT NULL,
    role varchar(50) not null,
    primary key (user_role_id),
    foreign key (username) references users(username)
);
create table if not exists book (
    id bigint generated by default as identity,
    image blob,
    content_type varchar(255),
    filename varchar(255),
    primary key (id)
)